steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/bigquery-project:$TAG_NAME', '--tag=gcr.io/$PROJECT_ID/bigquery-project:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/bigquery-project:latest', '/project/test.py']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bigquery-project:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'config', 'set', 'compute/zone', 'europe-west3-b']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instance-groups', 'managed', 'rolling-action', 'replace', 'configuration-backend-ag-igm']
images: ['gcr.io/$PROJECT_ID/bigquery-project:latest']